security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            security: true # Sécurisation par défaut, sauf exceptions spécifiées dans access_control

    access_control:
        # Accès libre pour les utilisateurs non connectés sur les pages publiques
        - { path: ^/(register|login|$), roles: PUBLIC_ACCESS }

        # Protège les pages nécessitant une authentification spécifique
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

