security:
    # Configuration des hashers de mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers pour charger les utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            custom_authenticators:
                - App\Security\UserAuthenticator
            provider: app_user_provider
            entry_point: App\Security\RedirectEntryPoint
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                username_parameter: _username
                password_parameter: _password
                always_use_default_target_path: false
            logout:
                path: app_logout
                invalidate_session: true
            # L'option `anonymous: true` est supprimée

    # Contrôles d'accès
    access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/.*, roles: ROLE_USER } 


